<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="0" passed="0" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-02T17:18:38 WIB" name="Suite" finished-at="2025-07-02T17:18:43 WIB" duration-ms="5077">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.zaidan.testng.runner.CucumberRunnerTests@1d9b7cce]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-07-02T17:18:38 WIB" name="Cucumber Reporting" finished-at="2025-07-02T17:18:43 WIB" duration-ms="5077">
      <class name="com.zaidan.testng.runner.CucumberRunnerTests">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.zaidan.testng.runner.CucumberRunnerTests@1d9b7cce]" started-at="2025-07-02T17:18:38 WIB" name="setUpClass" finished-at="2025-07-02T17:18:43 WIB" duration-ms="5011" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@f096f37]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test suite cannot proceed without database connection.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test suite cannot proceed without database connection.
at com.zaidan.testng.definitions.Hooks.setupSuite(Hooks.java:22)
Caused by: java.sql.SQLException: Failed to establish database connection through SSH tunnel.
at com.zaidan.testng.utils.DatabaseUtil.getConnection(DatabaseUtil.java:43)
at com.zaidan.testng.definitions.Hooks.setupSuite(Hooks.java:19)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
at org.postgresql.Driver.makeConnection(Driver.java:446)
at org.postgresql.Driver.connect(Driver.java:298)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:613)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:199)
at com.zaidan.testng.utils.DatabaseUtil.getConnection(DatabaseUtil.java:37)
... 1 more
Caused by: java.io.EOFException
at org.postgresql.core.PGStream.receiveChar(PGStream.java:469)
at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:594)
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:195)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
... 8 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.zaidan.testng.runner.CucumberRunnerTests@1d9b7cce]" started-at="2025-07-02T17:18:43 WIB" name="tearDownClass" finished-at="2025-07-02T17:18:43 WIB" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.zaidan.testng.runner.CucumberRunnerTests -->
    </test> <!-- Cucumber Reporting -->
  </suite> <!-- Suite -->
</testng-results>
